/**
 * Hubs (section 58) — each hub is a topic cluster that connects its articles.
 */
import type { Article, Hub } from "./types";

export const hubs: Hub[] = [
  { slug: "python", name: "Python", tagline: "The language I'm building the whole plan on top of.", accent: "#6D9D2D" },
  { slug: "ai-ml", name: "AI & Machine Learning", tagline: "Concepts explained for someone building toward them.", accent: "#147A70" },
  { slug: "problem-solving", name: "Problem Solving", tagline: "The thinking that happens before, during and after the code.", accent: "#6672C7" },
  { slug: "projects", name: "Projects", tagline: "Real builds, broken down into what was actually learned.", accent: "#B8F56A" },
  { slug: "software-development", name: "Software Development", tagline: "The craft of turning an idea into working software.", accent: "#7DE2D1" },
  { slug: "student-journey", name: "Student Developer", tagline: "Notes from inside a BSCS degree.", accent: "#A7B5FF" },
  { slug: "android", name: "Android Development", tagline: "The Java / XML / Firebase chapter.", accent: "#F59E0B" },
];

export const articles: Article[] = [
  {
    slug: "python-learning-roadmap",
    title: "A Realistic Python Learning Roadmap for Students",
    category: "Python",
    hub: "python",
    feat: true,
    primaryKeyword: "python learning roadmap",
    secondaryKeywords: ["python roadmap for beginners", "learn python as a student", "python study plan"],
    searchIntent: "Informational — plan a study path",
    audience: "BSCS students and self-learners starting Python",
    readingTime: 5,
    excerpt: "A concrete, week-by-week path through Python that a university student can actually follow — focused on building things, not collecting certificates.",
    readKeys: ["order of topics", "how many weeks", "project-first vs book-first"],
  },
  {
    slug: "python-functions-guide",
    title: "Python Functions: The Piece You'll Use Every Day",
    category: "Python",
    hub: "python",
    primaryKeyword: "python functions",
    secondaryKeywords: ["defining functions in python", "python def keyword", "python return vs print"],
    searchIntent: "Informational — core syntax",
    audience: "Beginner programmers solidifying Python fundamentals",
    readingTime: 5,
    excerpt: "Functions are the unit everything else in Python is built from. Here's how they actually work — scope, parameters, return values, and the details tutorials rush past.",
  },
  {
    slug: "python-oop-concepts",
    title: "Object-Oriented Programming in Python, Explained Slowly",
    category: "Python",
    hub: "python",
    primaryKeyword: "object oriented programming python",
    secondaryKeywords: ["python oop tutorial", "class and object in python", "python inheritance"],
    searchIntent: "Informational — concept + syntax",
    audience: "Learners who know Python basics and hit their first class keyword",
    readingTime: 5,
    excerpt: "Classes, objects, __init__, inheritance and encapsulation — the bits of OOP that finally click when you see them in a real, small program.",
  },
  {
    slug: "python-file-handling",
    title: "File Handling in Python for Real Projects",
    category: "Python",
    hub: "python",
    primaryKeyword: "file handling in python",
    secondaryKeywords: ["python read write files", "with open python", "python file modes"],
    searchIntent: "Informational — practical skill",
    audience: "Beginner-to-intermediate builders",
    readingTime: 5,
    excerpt: "Console programs become useful when they remember data. Reading, writing, appending, and the with statement — without the bugs everyone hits.",
  },
  {
    slug: "python-data-structures",
    title: "Python Data Structures You Actually Need First",
    category: "Python",
    hub: "python",
    primaryKeyword: "python data structures",
    secondaryKeywords: ["python list tuple dictionary", "python data structures for beginners", "when to use a dictionary"],
    searchIntent: "Informational — foundation",
    audience: "Beginners choosing between list, tuple, dict and set",
    readingTime: 5,
    excerpt: "Lists, tuples, dictionaries and sets — what each one is for, how to choose, and why dictionaries are the data structure you'll reach for constantly.",
  },
  {
    slug: "python-error-handling",
    title: "Python Error Handling Without the Panic",
    category: "Python",
    hub: "python",
    primaryKeyword: "python error handling",
    secondaryKeywords: ["try except python", "python exceptions tutorial", "handling errors in python"],
    searchIntent: "Informational — practical",
    audience: "Beginners whose programs crash on bad input",
    readingTime: 5,
    excerpt: "try, except, finally and when to let the error happen. Error handling is a feature of good programs — here's how to use it without hiding bugs.",
  },
  {
    slug: "python-standard-library",
    title: "8 Parts of the Python Standard Library Worth Knowing Early",
    category: "Python",
    hub: "python",
    primaryKeyword: "python standard library",
    secondaryKeywords: ["useful python modules", "python built-in modules", "os datetime json python"],
    searchIntent: "Informational — discovery",
    audience: "Learners moving past tutorials into real scripts",
    readingTime: 5,
    excerpt: "os, pathlib, json, csv, datetime, random, collections and itertools — the built-in modules that save you from reinventing (or pip-installing) the obvious.",
  },
  {
    slug: "python-virtual-environments",
    title: "Python Virtual Environments, Finally Explained",
    category: "Python",
    hub: "python",
    primaryKeyword: "python virtual environment",
    secondaryKeywords: ["how to use venv python", "activate virtual environment", "why use venv"],
    searchIntent: "Informational — tooling",
    audience: "Learners installing packages for the first time",
    readingTime: 5,
    excerpt: "What a venv actually is, why dependency hell happens, and the four commands that keep every project's packages from fighting each other.",
  },
  {
    slug: "python-vs-java",
    title: "Python vs Java: Which Should You Learn First?",
    category: "Python",
    hub: "python",
    primaryKeyword: "python vs java",
    secondaryKeywords: ["python or java for beginners", "difference between python and java", "java vs python for students"],
    searchIntent: "Comparison — decision support",
    audience: "Students (and switchers) choosing a first or next language",
    readingTime: 5,
    excerpt: "An honest comparison from someone learning both — where each language shines, where it annoys, and how to choose based on what you're building.",
  },
  {
    slug: "python-list-comprehensions",
    title: "Python List Comprehensions, Minus the Magic",
    category: "Python",
    hub: "python",
    primaryKeyword: "python list comprehension",
    secondaryKeywords: ["list comprehension examples", "python comprehension tutorial", "list comprehension vs for loop"],
    searchIntent: "Informational — idiom",
    audience: "Intermediate learners writing loop-heavy code",
    readingTime: 5,
    excerpt: "The one-line idiom that turns a five-line loop into a single expression — with real examples and a guide on when the loop is still better.",
  },
  {
    slug: "python-dictionaries-explained",
    title: "Python Dictionaries, Explained With Real Code",
    category: "Python",
    hub: "python",
    primaryKeyword: "python dictionary",
    secondaryKeywords: ["python dict methods", "iterate dictionary python", "dictionary in python example"],
    searchIntent: "Informational — foundation",
    audience: "Beginners and intermediates",
    readingTime: 5,
    excerpt: "fetch by key, setdefault, .get(), nested dicts and iteration — dictionaries are the workhorse of real Python, so here's everything daily use requires.",
  },
  {
    slug: "python-projects-beginners",
    title: "14 Python Projects That Teach More Than Tutorials",
    category: "Python",
    hub: "projects",
    primaryKeyword: "python projects for beginners",
    secondaryKeywords: ["beginner python project ideas", "python practice projects", "python projects to learn"],
    searchIntent: "Informational — ideas + motivation",
    audience: "Beginners who know syntax but haven't built enough",
    readingTime: 5,
    excerpt: "A project ladder from 'number guessing game' to 'file-backed CRUD app' — each one chosen because it forces a specific concept to actually work.",
  },
  {
    slug: "library-management-system-python",
    title: "How I Built a Library Management System in Python",
    category: "Projects",
    hub: "projects",
    primaryKeyword: "library management system python",
    secondaryKeywords: ["library management system project", "python console project", "library management system code"],
    searchIntent: "Project explanation + code walkthrough",
    audience: "Students building their first structured console app",
    readingTime: 5,
    excerpt: "A walk through my first real Python build — the menu loop, book records, and file handling that holds state between runs — with the design decisions explained.",
  },
  {
    slug: "student-management-system-python",
    title: "Building a Student Management System in Python",
    category: "Projects",
    hub: "projects",
    primaryKeyword: "student management system python",
    secondaryKeywords: ["student management system project", "python crud console app", "student record system"],
    searchIntent: "Project explanation + code walkthrough",
    audience: "Beginners building CRUD-style console applications",
    readingTime: 5,
    excerpt: "Add, save, search, display — the CRUD pattern at the heart of every record-keeping program, walkthrough included.",
  },
  {
    slug: "bank-management-system-python",
    title: "A Bank Management System in Python, Explained",
    category: "Projects",
    hub: "projects",
    primaryKeyword: "bank management system python",
    secondaryKeywords: ["bank management system project", "python banking console app", "account deposit withdraw python"],
    searchIntent: "Project explanation + code walkthrough",
    audience: "Beginners practicing state and transaction logic",
    readingTime: 5,
    excerpt: "Accounts, deposits, withdrawals and balance checks — a fictional-lab version that teaches real transaction logic and object state.",
  },
  {
    slug: "console-app-design",
    title: "Designing a Console App That Doesn't Feel Like Spaghetti",
    category: "Software Development",
    hub: "software-development",
    primaryKeyword: "python console application",
    secondaryKeywords: ["console app structure", "python menu loop", "organizing python project"],
    searchIntent: "Informational — structure",
    audience: "Beginners whose single-file programs got unmanageable",
    readingTime: 5,
    excerpt: "The difference between a script and a program — menu loops, separation of concerns, and the structure that made the management systems maintainable.",
  },
  {
    slug: "python-project-structure",
    title: "How to Structure a Python Project From Day One",
    category: "Software Development",
    hub: "software-development",
    primaryKeyword: "python project structure",
    secondaryKeywords: ["how to organize python project", "python folder structure", "python project layout"],
    searchIntent: "Informational — organization",
    audience: "Learners whose projects outgrew one file",
    readingTime: 5,
    excerpt: "A simple folder layout that won't fight you at 2 a.m. — modules, packages, config, data files, and a README people will actually read.",
  },
  {
    slug: "readme-that-works",
    title: "Writing a README That Makes People Care About Your Project",
    category: "Software Development",
    hub: "projects",
    primaryKeyword: "how to write a readme",
    secondaryKeywords: ["readme template github", "good readme examples", "project documentation"],
    searchIntent: "Informational / practical",
    audience: "Students pushing projects to GitHub",
    readingTime: 5,
    excerpt: "Your project has seconds to earn attention. A concrete structure for a README that explains, screenshots, and genuinely helps.",
  },
  {
    slug: "what-is-artificial-intelligence",
    title: "What Artificial Intelligence Actually Is (And Isn't)",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "what is artificial intelligence",
    secondaryKeywords: ["artificial intelligence explained", "ai definition for beginners", "what is ai really"],
    searchIntent: "Informational — definition",
    audience: "Anyone starting AI from the very beginning",
    readingTime: 5,
    excerpt: "Cutting through the hype: what AI means technically, what it can do today, and the honest gap between fiction and current systems.",
  },
  {
    slug: "machine-learning-basics",
    title: "Machine Learning Basics: What “Learning” Means to a Machine",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "machine learning basics",
    secondaryKeywords: ["machine learning beginner", "how does machine learning work", "ml explained simply"],
    searchIntent: "Informational — concept intro",
    audience: "Beginners approaching ML with Python background only",
    readingTime: 5,
    excerpt: "A model is a guess that corrects itself. This is the mental model behind supervised learning — no PhD required.",
  },
  {
    slug: "supervised-vs-unsupervised",
    title: "Supervised vs Unsupervised Learning, in Plain English",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "supervised vs unsupervised learning",
    secondaryKeywords: ["difference between supervised and unsupervised", "labeled vs unlabeled data", "types of machine learning"],
    searchIntent: "Comparison — concept distinction",
    audience: "ML beginners mapping the territory",
    readingTime: 5,
    excerpt: "The difference between labeled and unlabeled data — and why that one distinction defines two entire families of algorithms.",
  },
  {
    slug: "what-is-a-dataset",
    title: "What a Dataset Is (And Why “Data” Is a Skill)",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "what is a dataset",
    secondaryKeywords: ["dataset meaning", "structured vs unstructured data", "data for machine learning"],
    searchIntent: "Informational — concept",
    audience: "Beginners learning the data side of ML",
    readingTime: 5,
    excerpt: "Datasets are the raw material of machine learning. What they look like, what “clean” means, and why data prep eats most of the time.",
  },
  {
    slug: "linear-regression-explained",
    title: "Linear Regression Explained Like You Have a Whiteboard",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "linear regression explained",
    secondaryKeywords: ["linear regression simple explanation", "linear regression for beginners", "fitting a line to data"],
    searchIntent: "Informational — first ML algorithm",
    audience: "Beginners meeting their first learning algorithm",
    readingTime: 5,
    excerpt: "Drawing the best line through points — the algorithm that introduces features, weights, prediction and error all in one sitting.",
  },
  {
    slug: "free-ml-learning-path",
    title: "A Free Machine Learning Path That Starts With Python",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "machine learning roadmap",
    secondaryKeywords: ["how to start machine learning", "ml learning path for programmers", "free machine learning resources"],
    searchIntent: "Informational — roadmap",
    audience: "Programmers plotting a path into ML",
    readingTime: 5,
    excerpt: "From Python fluency → data → math → first models: a path a working student can move down without quitting their degree (or their budget).",
  },
  {
    slug: "python-for-machine-learning",
    title: "Why Python Is the Language of Machine Learning",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "python for machine learning",
    secondaryKeywords: ["why python for ml", "python ml libraries", "is python enough for machine learning"],
    searchIntent: "Informational — why",
    audience: "Beginners choosing where to invest language time",
    readingTime: 5,
    excerpt: "It's not hype — but it's also not magic. The ecosystem reason Python dominates ML, and the libraries you'll meet first.",
  },
  {
    slug: "pandas-first-steps",
    title: "Your First Steps With Pandas for Data Work",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "pandas tutorial for beginners",
    secondaryKeywords: ["python pandas basics", "read csv pandas", "dataframe tutorial"],
    searchIntent: "Tutorial — first steps",
    audience: "Python users starting data manipulation",
    readingTime: 5,
    excerpt: "A tight introduction to pandas: the DataFrame, reading CSVs, selecting rows, and the three functions you'll use in the first week.",
  },
  {
    slug: "ai-ml-mistakes-beginners",
    title: "6 Mistakes When Learning Machine Learning (And How to Avoid Them)",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "machine learning mistakes beginners",
    secondaryKeywords: ["learning ml wrong way", "ml beginner mistakes", "common ai learning mistakes"],
    searchIntent: "Informational — pitfalls",
    audience: "Self-learners avoiding the usual dead ends",
    readingTime: 5,
    excerpt: "Skipping Python, memorizing math instead of building, collecting courses instead of models — the traps and their simple fixes.",
  },
  {
    slug: "ai-project-ideas-students",
    title: "AI & ML Project Ideas You Can Actually Finish as a Student",
    category: "AI ML",
    hub: "ai-ml",
    primaryKeyword: "machine learning project ideas",
    secondaryKeywords: ["ai projects for students", "beginner ml projects", "small ml projects"],
    searchIntent: "Informational — ideas",
    audience: "Students building a first ML portfolio piece",
    readingTime: 5,
    excerpt: "Small, honest ML projects — from irises to your own data — each scoped so a student can actually ship it and explain it.",
  },
  {
    slug: "thinking-before-coding",
    title: "The Problem Before the Code: Thinking, Then Typing",
    category: "Problem Solving",
    hub: "problem-solving",
    primaryKeyword: "how to think like a programmer",
    secondaryKeywords: ["problem solving programming", "think before coding", "problem solving in software"],
    searchIntent: "Informational — mindset",
    audience: "Learners who start typing before understanding",
    readingTime: 5,
    excerpt: "The habit that separates fast learners: understand, break down, design, then build. The workflow that goes into every project here.",
  },
  {
    slug: "break-down-problems",
    title: "How to Break a Big Problem Into Small Pieces",
    category: "Problem Solving",
    hub: "problem-solving",
    primaryKeyword: "how to break down a programming problem",
    secondaryKeywords: ["divide and conquer programming", "problem decomposition", "break large task into steps"],
    searchIntent: "How-to — technique",
    audience: "Beginners overwhelmed by big assignments",
    readingTime: 5,
    excerpt: "Decomposition is a skill, not a talent. A repeatable method for turning 'I don't know where to start' into a list of solvable steps.",
  },
  {
    slug: "debugging-strategies",
    title: "Debugging Like Someone Who Actually Finds the Bug",
    category: "Problem Solving",
    hub: "problem-solving",
    primaryKeyword: "debugging strategies",
    secondaryKeywords: ["how to debug code", "debugging tips for beginners", "find bugs faster"],
    searchIntent: "How-to — technique",
    audience: "Beginners losing hours to broken code",
    readingTime: 6,
    excerpt: "Print statements are a start, not the whole toolset. A calm, systematic route from “it's broken” to “it's fixed” — and why reading the error matters.",
  },
  {
    slug: "programming-logic",
    title: "Programming Logic: The Skill Before Every Language",
    category: "Problem Solving",
    hub: "problem-solving",
    primaryKeyword: "programming logic for beginners",
    secondaryKeywords: ["programming logic concepts", "logic building in programming", "how to improve coding logic"],
    searchIntent: "Informational — foundation",
    audience: "Beginners who feel lost past basic syntax",
    readingTime: 5,
    excerpt: "Conditionals, loops, functions and state — the four building blocks of every program, and how to think in them deliberately.",
  },
  {
    slug: "beginner-mistakes-python",
    title: "Common Beginner Programming Mistakes (That Aren't Syntax Errors)",
    category: "Problem Solving",
    hub: "problem-solving",
    primaryKeyword: "common programming mistakes beginners",
    secondaryKeywords: ["beginner coding mistakes", "python beginner mistakes", "bad programming habits"],
    searchIntent: "Informational — pitfalls",
    audience: "Self-taught and student learners",
    readingTime: 5,
    excerpt: "Not reading errors, building too big, skipping small wins — the mistakes that stall progress more than any missing concept.",
  },
  {
    slug: "tutorial-to-project",
    title: "From Tutorial Hell to Real Projects: The Bridge",
    category: "Problem Solving",
    hub: "student-journey",
    primaryKeyword: "tutorial hell",
    secondaryKeywords: ["how to stop watching tutorials", "move from tutorials to building", "tutorial to project transition"],
    searchIntent: "Problem/solution — motivation",
    audience: "Learners stuck in tutorial loops",
    readingTime: 5,
    excerpt: "Tutorials feel like progress but often aren't. The practical steps that turn watching into building — with the projects that did it for me.",
  },
  {
    slug: "coding-challenges-benefits",
    title: "Do Coding Challenges Actually Make You Better?",
    category: "Problem Solving",
    hub: "problem-solving",
    primaryKeyword: "coding challenges for beginners",
    secondaryKeywords: ["do coding challenges work", "coding practice problems", "best way to practice coding"],
    searchIntent: "How-to / opinion — practice",
    audience: "Learners designing a practice routine",
    readingTime: 5,
    excerpt: "Short answer: yes, if they're treated as thinking practice, not typing practice. How to do challenges that transfer to real projects.",
  },
  {
    slug: "learn-programming-as-student",
    title: "Learning Programming as a CS Student (Without Burning Out)",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "how to learn programming as a student",
    secondaryKeywords: ["computer science student advice", "self study for cs students", "balancing university and coding"],
    searchIntent: "How-to / mindset",
    audience: "BSCS students in their first and second years",
    readingTime: 5,
    excerpt: "University teaches theory; projects teach understanding. How to run both at once, use courses as scaffolding, and keep momentum.",
  },
  {
    slug: "first-programming-language",
    title: "Choosing Your First Programming Language as a Student",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "how to choose a programming language",
    secondaryKeywords: ["best first language", "python or java first", "first programming language for students"],
    searchIntent: "Decision support",
    audience: "Students choosing where to start",
    readingTime: 5,
    excerpt: "There's no perfect first language, but there is a perfect first question: what do you want to build? A decision framework that survives graduation.",
  },
  {
    slug: "building-projects-while-studying",
    title: "Building Projects While Studying: A Working Student's System",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "programming projects for students",
    secondaryKeywords: ["balance study and projects", "student developer projects", "projects during university"],
    searchIntent: "How-to — practical",
    audience: "Students who want a portfolio before graduation",
    readingTime: 5,
    excerpt: "You don't need a year off to build. The small-project system — one concept per project, one commit at a time — that fits around a timetable.",
  },
  {
    slug: "github-for-students",
    title: "GitHub for Students: Your First Repositories, Explained",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "github for beginners",
    secondaryKeywords: ["how to use github for students", "git vs github", "first github repository"],
    searchIntent: "Tutorial — tooling",
    audience: "Students opening their first GitHub account",
    readingTime: 5,
    excerpt: "What GitHub does, the commit/push/pull loop, and how one account slowly turns into proof of how you work — beyond grades.",
  },
  {
    slug: "preparing-for-internships",
    title: "Preparing for Your First Software Internship, Honestly",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "software internship preparation",
    secondaryKeywords: ["how to prepare for internship", "student internship roadmap", "first internship as developer"],
    searchIntent: "How-to — preparation",
    audience: "Students targeting first developer internships",
    readingTime: 5,
    excerpt: "Projects over certificates, the fundamentals interviewers actually test, and how to present “student” work without overselling it.",
  },
  {
    slug: "developer-portfolio-guide",
    title: "How to Build a Developer Portfolio That Represents You",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "how to make a developer portfolio",
    secondaryKeywords: ["student developer portfolio", "portfolio for beginners", "what to put in a portfolio"],
    searchIntent: "How-to — practical",
    audience: "Students building (this site included)",
    readingTime: 5,
    excerpt: "Not a résumé in web form — a story with evidence. What belongs, what gets cut, and the honesty rule that makes a portfolio trustworthy.",
  },
  {
    slug: "computer-science-vs-software-engineering",
    title: "Computer Science vs Software Engineering (For People Deciding)",
    category: "Student Journey",
    hub: "student-journey",
    primaryKeyword: "computer science vs software engineering",
    secondaryKeywords: ["difference between cs and se", "which degree to choose", "cs or software engineering"],
    searchIntent: "Comparison — decision support",
    audience: "Prospective and first-year students",
    readingTime: 5,
    excerpt: "Theory vs construction — and why the distinction matters less than what you build alongside either degree.",
  },
  {
    slug: "android-app-architecture-beginners",
    title: "Android App Architecture for Beginners (Without the Jargon)",
    category: "Android",
    hub: "android",
    primaryKeyword: "android app architecture",
    secondaryKeywords: ["android project structure", "mvvm for beginners", "organizing android project"],
    searchIntent: "Informational — structure",
    audience: "Learners whose Android project outgrew one activity",
    readingTime: 5,
    excerpt: "Activities, layouts, and keeping logic out of the UI — a plain-English look at the structure that keeps an e-commerce app maintainable.",
  },
  {
    slug: "java-android-development",
    title: "Learning Android Development With Java and XML",
    category: "Android",
    hub: "android",
    primaryKeyword: "android development with java",
    secondaryKeywords: ["java android studio tutorial", "xml layouts android", "android development for beginners"],
    searchIntent: "Tutorial / overview",
    audience: "Beginners starting Android with Java",
    readingTime: 5,
    excerpt: "The Java + XML foundation of Android: what each file does, how layouts and code talk, and the first app worth building.",
  },
  {
    slug: "firebase-auth-android",
    title: "Firebase Authentication in Android, Step by Step",
    category: "Android",
    hub: "android",
    primaryKeyword: "firebase authentication android",
    secondaryKeywords: ["firebase login android", "email password auth firebase", "firebase auth setup"],
    searchIntent: "Tutorial — feature",
    audience: "Android learners adding login to their app",
    readingTime: 5,
    excerpt: "Email/password login end to end with Firebase — setup, wiring, error handling, and the mistakes that show up in logs at 1 a.m.",
  },
  {
    slug: "cloud-firestore-basics",
    title: "Cloud Firestore vs SQLite: The Right Tool for the Job",
    category: "Android",
    hub: "android",
    primaryKeyword: "cloud firestore vs sqlite",
    secondaryKeywords: ["firestore for beginners", "sqlite vs firebase", "local vs cloud database android"],
    searchIntent: "Comparison — decision support",
    audience: "Android/data learners choosing a backend",
    readingTime: 5,
    excerpt: "Local data stays on the device; Firestore lives in the cloud. Understanding when each one earns its place — from an app with both in its stack.",
  },
  {
    slug: "shopping-cart-logic-android",
    title: "Building Shopping Cart Logic in an Android App",
    category: "Android",
    hub: "android",
    primaryKeyword: "android shopping cart",
    secondaryKeywords: ["shopping cart logic", "add to cart android app", "cart functionality java"],
    searchIntent: "Tutorial / concept",
    audience: "Android beginners building e-commerce features",
    readingTime: 5,
    excerpt: "The data model behind an e-commerce cart — line items, quantities, totals, and the persistence choices that keep a cart sane.",
  },
  {
    slug: "material-design-android",
    title: "Material Design for Android: Why It Makes Apps Feel Finished",
    category: "Android",
    hub: "android",
    primaryKeyword: "material design android",
    secondaryKeywords: ["material design principles", "material components android", "android ui design"],
    searchIntent: "Informational — design system",
    audience: "Android learners who want polished UI",
    readingTime: 5,
    excerpt: "Material Design isn't a theme — it's a set of decisions made for you. Using it well is what makes a student app feel professional.",
  },
  {
    slug: "sneakerstore-ecommerce-app",
    title: "SneakerStore: Building a Full E-Commerce Android App as a Student",
    category: "Projects",
    hub: "projects",
    feat: true,
    primaryKeyword: "ecommerce android app project",
    secondaryKeywords: ["sneaker shopping app android", "java ecommerce app project", "firebase shopping app"],
    searchIntent: "Project case study",
    audience: "Students attempting their first full-stack Android build",
    readingTime: 5,
    excerpt: "The story of SneakerStore — authentication, product browsing, cart, address management — the architecture and the hard parts, honestly.",
  },
  {
    slug: "git-commands-you-need",
    title: "Git Commands You'll Actually Use Every Day",
    category: "Software Development",
    hub: "software-development",
    primaryKeyword: "git commands",
    secondaryKeywords: ["git basics", "basic git commands tutorial", "git commit push pull"],
    searchIntent: "Tutorial — reference",
    audience: "Learners adopting version control for real",
    readingTime: 5,
    excerpt: "not the 40-command cheat sheet — the seven commands that carry 95% of daily work, explained with an actual workflow.",
  },
  {
    slug: "git-vs-github",
    title: "Git vs GitHub: The Difference That Finally Makes Sense",
    category: "Software Development",
    hub: "software-development",
    primaryKeyword: "git vs github",
    secondaryKeywords: ["difference between git and github", "is github git", "git and github for beginners"],
    searchIntent: "Informational — clarification",
    audience: "Beginners confusing tool with platform",
    readingTime: 5,
    excerpt: "Git is the version tracker; GitHub is where the repos live. A two-minute mental model that sorts every future confusion.",
  },
];
