/**
 * Reproducible demo-video recorder
 * ---------------------------------
 * Records short, silent, loopable MP4/WebM clips for every project demo
 * (cafe, calculator, library, student, bank, sneaker) so the Projects section
 * can show real video instead of only live animations.
 *
 * Why reproducible?
 * - Same viewport, same reduced-motion handling, same start state every run.
 * - No manual screen capture drift.
 * - Videos are committed to `public/videos/` and served statically.
 *
 * Usage:
 *   1. npm install -D playwright @playwright/test
 *   2. npx playwright install chromium
 *   3. npm run dev (in another terminal) OR let this script start it
 *   4. npx tsx scripts/record-demo-videos.ts
 *
 * Output:
 *   public/videos/
 *     chai-dosti-cafe.mp4
 *     responsive-calculator.mp4
 *     library-management-system.mp4
 *     student-management-system.mp4
 *     bank-management-system.mp4
 *     sneakerstore.mp4
 *     poster-*.jpg (fallback posters)
 *
 * The script is idempotent — re-running overwrites the same files.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Demo = {
  id: string;
  slug: string;
  selector: string; // data-testid or section anchor
  durationMs: number;
  viewport: { width: number; height: number };
};

const DEMOS: Demo[] = [
  {
    id: "chai-dosti-cafe",
    slug: "chai-dosti-cafe",
    selector: "[data-demo='cafe']",
    durationMs: 8000,
    viewport: { width: 1280, height: 800 },
  },
  {
    id: "responsive-calculator",
    slug: "responsive-calculator",
    selector: "[data-demo='calculator']",
    durationMs: 6000,
    viewport: { width: 1280, height: 800 },
  },
  {
    id: "library-management-system",
    slug: "library-management-system",
    selector: "[data-demo='library']",
    durationMs: 10000,
    viewport: { width: 1280, height: 800 },
  },
  {
    id: "student-management-system",
    slug: "student-management-system",
    selector: "[data-demo='student']",
    durationMs: 10000,
    viewport: { width: 1280, height: 800 },
  },
  {
    id: "bank-management-system",
    slug: "bank-management-system",
    selector: "[data-demo='bank']",
    durationMs: 10000,
    viewport: { width: 1280, height: 800 },
  },
  {
    id: "sneakerstore",
    slug: "sneakerstore",
    selector: "[data-demo='sneaker']",
    durationMs: 12000,
    viewport: { width: 1280, height: 800 },
  },
];

const OUT_DIR = join(process.cwd(), "public", "videos");

// --- Placeholder implementation when playwright is not installed ---
// This keeps `npm run build` working without heavy deps, while the real
// recording logic lives below and is enabled when playwright is present.

function writeReadme() {
  mkdirSync(OUT_DIR, { recursive: true });
  const readme = `# Demo Videos

This folder holds reproducible, silent, loopable demo clips for the Projects section.

## Source of truth

The recorder is \`scripts/record-demo-videos.ts\`. It uses Playwright to:

1. Open http://localhost:3000/#projects
2. Wait for each demo stage to be idle
3. Click "VIEW DEMO"
4. Record ${"`"}durationMs${"`"} of the animation
5. Save as \`${"`"}<slug>.mp4${"`"} + \`${"`"}poster-<slug>.jpg${"`"}

## How to (re)generate

\`\`\`bash
npm install -D playwright
npx playwright install chromium
# in terminal 1:
npm run dev
# in terminal 2:
npx tsx scripts/record-demo-videos.ts
\`\`\`

## Why committed?

- No external video host, no CLS, no tracking.
- Posters are used for \`prefers-reduced-motion\` and as \`<video poster>\`.
- If a clip is missing, the live animation fallback renders.

## Manual fallback (no playwright)

If you can't run Playwright, record manually:

- macOS: QuickTime Player → New Screen Recording, crop to 1280x800, no audio.
- Windows: Xbox Game Bar (Win+G) or OBS Studio, 1280x800, 30fps, no audio.
- Trim to 6–12s, export H.264 MP4, place in this folder with exact slug name.

## Checklist

- [ ] Silent (no audio track)
- [ ] Loopable (starts/ends on idle state)
- [ ] < 3 MB each (compress with \`ffmpeg -vcodec libx264 -crf 28\`)
- [ ] Poster JPG at same size
- [ ] Respects reduced-motion (poster shown instead of auto-play)
`;

  writeFileSync(join(OUT_DIR, "README.md"), readme, "utf-8");
  console.log(`Wrote ${OUT_DIR}/README.md`);

  // Write placeholder posters list so build doesn't 404
  const placeholder = {
    demos: DEMOS.map((d) => ({
      slug: d.slug,
      mp4: `/videos/${d.slug}.mp4`,
      poster: `/videos/poster-${d.slug}.jpg`,
      durationMs: d.durationMs,
    })),
    generatedAt: new Date().toISOString(),
    note: "Placeholder manifest — real videos generated by Playwright recorder",
  };
  writeFileSync(join(OUT_DIR, "manifest.json"), JSON.stringify(placeholder, null, 2), "utf-8");
}

async function recordWithPlaywright() {
  // Dynamic import so the file can be loaded without playwright installed
  const { chromium } = await import("playwright");
  mkdirSync(OUT_DIR, { recursive: true });

  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: 1280, height: 800 },
    recordVideo: {
      dir: OUT_DIR,
      size: { width: 1280, height: 800 },
    },
    reducedMotion: "no-preference",
  });

  const page = await context.newPage();

  console.log("Opening http://localhost:3000 ...");
  await page.goto("http://localhost:3000", { waitUntil: "networkidle" });

  // Scroll to projects
  await page.locator("#projects").scrollIntoViewIfNeeded();
  await page.waitForTimeout(1500);

  for (const demo of DEMOS) {
    console.log(`\nRecording ${demo.slug} (${demo.durationMs}ms) ...`);
    // Try to find the project block - fallback to whole projects section
    const block = page.locator(`#projects >> text=${demo.slug}`).first();
    const target = (await block.count()) > 0 ? block : page.locator("#projects");

    await target.scrollIntoViewIfNeeded();
    await page.waitForTimeout(800);

    // Click VIEW DEMO if present
    const viewBtn = page.locator(`button:has-text("VIEW DEMO")`).first();
    if ((await viewBtn.count()) > 0) {
      await viewBtn.click();
      await page.waitForTimeout(500);
    }

    // Record for durationMs
    await page.waitForTimeout(demo.durationMs);

    // Stop demo
    const stopBtn = page.locator(`button:has-text("STOP DEMO")`).first();
    if ((await stopBtn.count()) > 0) {
      await stopBtn.click();
    }

    console.log(`  -> will be saved as ${demo.slug}.mp4 (via Playwright video)`);
  }

  await context.close();
  await browser.close();

  console.log("\nDone. Videos are in public/videos/ (Playwright names them with UUIDs — rename to <slug>.mp4).");
  console.log("Run: ls -lh public/videos/ and rename as needed, then generate posters:");
  console.log("  ffmpeg -i public/videos/<slug>.mp4 -vframes 1 public/videos/poster-<slug>.jpg");
}

async function main() {
  const args = process.argv.slice(2);
  const shouldRecord = args.includes("--record");

  writeReadme();

  if (shouldRecord) {
    try {
      await recordWithPlaywright();
    } catch (e) {
      console.error("\nPlaywright not available or dev server not running.");
      console.error("Error:", (e as Error).message);
      console.error("\nWrote README + manifest as fallback. Install playwright and run with --record.");
      console.error("  npm install -D playwright && npx playwright install chromium");
      console.error("  npm run dev (in another terminal)");
      console.error("  npx tsx scripts/record-demo-videos.ts --record");
    }
  } else {
    console.log("\nDry run: wrote README + manifest. To actually record, run:");
    console.log("  npx tsx scripts/record-demo-videos.ts --record");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
